# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker run --platform linux/x86_64 --name jamcaa-mysql -e MYSQL_USER=jamcaa -e MYSQL_PASSWORD=jamcaa -e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=root -p 6603:3306 -d mysql:5.7
    - run: npm install
    - run: npm test
    - run: docker stop jamcaa-mysql
    - run: docker rm jamcaa-mysql
